### ISSUE TITLE
Unable to use Flexpilot AI in WSL2

### ISSUE THREAD

**Issue by avcode-exe** [flexpilot-ai/vscode-extension#1]
Hi, very impressive extension! Keep up the good works!

I want to use Flexpilot in WSL2 Ubuntu in Vscode, however it doesn't show up after installation. I've tried to reload the windows, but it still doesn't show up.

Btw, I disabled Github Copilot and Github Copilot Chat.

Log from Flexpilot:
```
2024-11-05 22:58:38.140 [info] StorageManager instance created
2024-11-05 22:58:38.140 [debug] Getting global state for key: argv.path
2024-11-05 22:58:38.140 [debug] Extension ID: flexpilot.flexpilot-vscode-extension
2024-11-05 22:58:38.140 [error] Error: ENOENT: no such file or directory, open 'c:/Users/Tom/.vscode/argv.json'
	at Object.readFileSync (node:fs:448:20)
	at /home/airtau/.vscode-server/extensions/flexpilot.flexpilot-vscode-extension-1.95.0/out/extension.js:2:1311127
	at t.updateRuntimeArguments (/home/airtau/.vscode-server/extensions/flexpilot.flexpilot-vscode-extension-1.95.0/out/extension.js:2:1312089)
	at e.activate (/home/airtau/.vscode-server/extensions/flexpilot.flexpilot-vscode-extension-1.95.0/out/extension.js:2:2192179)
	at pw.kb (file:///home/airtau/.vscode-server/bin/65edc4939843c90c34d61f4ce11704f09d3e5cb6/out/vs/workbench/api/node/extensionHostProcess.js:118:15214)
	at pw.jb (file:///home/airtau/.vscode-server/bin/65edc4939843c90c34d61f4ce11704f09d3e5cb6/out/vs/workbench/api/node/extensionHostProcess.js:118:14921)
	at file:///home/airtau/.vscode-server/bin/65edc4939843c90c34d61f4ce11704f09d3e5cb6/out/vs/workbench/api/node/extensionHostProcess.js:118:13079
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async B0.n (file:///home/airtau/.vscode-server/bin/65edc4939843c90c34d61f4ce11704f09d3e5cb6/out/vs/workbench/api/node/extensionHostProcess.js:114:4447)
	at async B0.m (file:///home/airtau/.vscode-server/bin/65edc4939843c90c34d61f4ce11704f09d3e5cb6/out/vs/workbench/api/node/extensionHostProcess.js:114:4410)
	at async B0.l (file:///home/airtau/.vscode-server/bin/65edc4939843c90c34d61f4ce11704f09d3e5cb6/out/vs/workbench/api/node/extensionHostProcess.js:114:3866)
2024-11-05 22:58:38.140 [debug] Set context: isLoaded = false
2024-11-05 22:58:38.140 [debug] Set context: isError = false
2024-11-05 22:58:38.140 [debug] Set context: isLoggedIn = false
2024-11-05 22:58:38.140 [debug] Set context: isError = true
```
Sidebar:
![image](https://github.com/user-attachments/assets/69cf615f-c73f-4580-8c8f-bc0b41c07400)

**Comment by NeelBI** [comment]
From VS Code 1.95 onwards the extension is by default on the right pane. If you look at the top, there will be a copilot icon which you can click to select panel chat. Is that visible? Alternatively, you can just press ctrl+I on your editor to check if quick chat opens up. If neither works, please confirm and we will have it checked. Thank you for reporting the issue.

**Comment by avcode-exe** [comment]
Here is the screen shot of my vscode.
![image](https://github.com/user-attachments/assets/77c20afb-4863-4d0f-906d-c0ab3f6596ce)
Also when I clicked on the copilot icon on the top, it redirected me to enable the github copilot extension.
![image](https://github.com/user-attachments/assets/ca179f9a-5279-487d-a000-5d6eac77ebd3)
Ctrl+I doesn't work too.

**Comment by mohankumarelec** [comment]
@avcode-exe , Thanks a lot for testing out our extension. The error you are seeing is because we are currently using the Node fs library directly to update argv.json, Due to which its not working when using remote tunnels. 

I am working on the fix for this to move to vscode.workspace.fs instead of node fs, and will keep this thread alive and posted on the progress.

**Comment by will-0** [comment]
Hi, thanks for the work on this! Just to second the above, am getting the same error when attempting to install in a dev container.

**Comment by NeelBI** [comment]
Will address that as well , can you please pass on the logs?

**Comment by mohankumarelec** [comment]
Hi @avcode-exe, @will-0! 🎉 

We just launched FlexPilot version **1.95.1**, which now supports **remote servers** like **SSH**, **WSL**, and more! 🚀

Please give it a try and let us know about your experience. Your feedback would be invaluable!

Thank you so much! 🙏

**Comment by mhykes** [comment]
I'm seeing this error again in v1.95.2.
```

2024-11-20 19:46:18.087 [debug] Getting global state for key: argv.path
2024-11-20 19:46:18.087 [debug] Extension ID: flexpilot.flexpilot-vscode-extension
2024-11-20 19:46:18.095 [debug] Set context: isLoaded = false
2024-11-20 19:46:18.095 [debug] Set context: isError = false
2024-11-20 19:46:18.095 [debug] Set context: isLoggedIn = false
2024-11-20 19:46:18.205 [error] EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'c:/Users/Matth/.vscode/argv.json'
	at Ji.e (file:///vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:114:9057)
	at Object.readFile (file:///vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:114:7581)
	at async /root/.vscode-server/extensions/flexpilot.flexpilot-vscode-extension-1.95.2-linux-x64/out/277.extension.js:1:102323
	at async t.updateRuntimeArguments (/root/.vscode-server/extensions/flexpilot.flexpilot-vscode-extension-1.95.2-linux-x64/out/277.extension.js:1:101684)
	at async t.activate (/root/.vscode-server/extensions/flexpilot.flexpilot-vscode-extension-1.95.2-linux-x64/out/277.extension.js:1:28737)
	at async a.activate (/root/.vscode-server/extensions/flexpilot.flexpilot-vscode-extension-1.95.2-linux-x64/out/extension.js:2:31390)
	at async B0.n (file:///vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:114:4447)
	at async B0.m (file:///vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:114:4410)
	at async B0.l (file:///vscode/vscode-server/bin/linux-x64/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:114:3866)
2024-11-20 19:46:18.226 [warning] EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'c:/Users/Matth/.vscode/argv.json'
```
Maybe because I have
```
  "remote.extensionKind": {
    "flexpilot.flexpilot-vscode-extension": [ "workspace" ]
  }
```

I have a local AI service that I don't want to expose outside of my devcontainer, but do want Flexpilot to use.  So Flexpilot needs to run in the container.  Any leads on how can I get this working?

**Comment by mohankumarelec** [comment]
Hi @mhykes ,  

Thank you for bringing up this issue! 🙏  

Yes, the behavior is due to the following setting:  

```json
"remote.extensionKind": {
  "flexpilot.flexpilot-vscode-extension": ["workspace"]
}
```  

Currently, the extension is designed to run in **UI mode** rather than **workspace mode**. This limitation stems from the way VS Code handles data storage:  
- **Global state** is stored in the UI context.  
- **Global storage** is limited in the workspace context.  

Unfortunately, at this time, we don't have a workaround for this limitation. However, we understand the importance of supporting this feature and have added it to our roadmap. We'll explore potential solutions and aim to provide support for this in the future.  

Thank you for your patience and understanding!

**Comment by avcode-exe** [comment]
> Hi @avcode-exe, @will-0! 🎉
> 
> We just launched FlexPilot version **1.95.1**, which now supports **remote servers** like **SSH**, **WSL**, and more! 🚀
> 
> Please give it a try and let us know about your experience. Your feedback would be invaluable!
> 
> Thank you so much! 🙏

Sorry for the late reply! But it is working!

**Comment by lgonzalezsa** [comment]
Trying to use Remote - SSH version 0.120.0 but seems is only supported in Microsoft versions of VS Code

![Image](https://github.com/user-attachments/assets/8d834041-27b5-4019-a643-ed3b12bb9d83)
