### ISSUE TITLE
Unable to use Flexpilot in vscode - Continuos Restarts

### ISSUE THREAD

**Issue by Thedrassbass** [flexpilot-ai/vscode-extension#2]
Unable to use Flexpilot in vscode due to a continuos restart of flexpilot telling the system to restart vscode to configure a setting, have been popping up over 50 times now and i have been trying to grant it that but as soon as i click on yes it restarts vscode, then telling me to restart it again.

![image](https://github.com/user-attachments/assets/497faf84-6cd1-425d-b4c2-edab8fba9305)

**Comment by NeelBI** [comment]
Hey thanks for reporting. Would you please be able to send detailed logs from terminal as well for us to debug further?

**Comment by Deathdadev** [comment]
Same issue here. I see that they didn't give you their logs, so here are mine:

**Comment by Deathdadev** [comment]
Same issue here. I see that they didn't give you their logs, so here are mine:
```
2025-01-09 20:00:59.201 [info] StorageManager instance created
2025-01-09 20:00:59.202 [info] VS Code Version: 1.96.2
2025-01-09 20:00:59.202 [info] Node Version: v20.18.1
2025-01-09 20:00:59.202 [info] Platform: win32
2025-01-09 20:00:59.202 [info] CPU Architecture: x64
2025-01-09 20:00:59.202 [info] Extension ID: flexpilot.flexpilot-vscode-extension
2025-01-09 20:00:59.202 [info] Extension Version: 1.96.3
2025-01-09 20:00:59.202 [info] Extension Path: c:\Users\User\.vscode\extensions\flexpilot.flexpilot-vscode-extension-1.96.3-win32-x64
2025-01-09 20:00:59.202 [info] Workspace Name: ModernUI
2025-01-09 20:00:59.202 [info] Workspace URI: file:///c%3A/Users/User/Documents/github/ModernUI
2025-01-09 20:00:59.202 [info] Environment Variables: I'm hiding this
2025-01-09 20:00:59.202 [info] EventsSingleton instance created
2025-01-09 20:00:59.202 [info] StatusIconManager instance created
2025-01-09 20:00:59.202 [info] ModelProviderManager instance created
2025-01-09 20:00:59.202 [info] No provider found for location Inline Completion
2025-01-09 20:00:59.202 [error] Error: Extension 'flexpilot.flexpilot-vscode-extension' CANNOT use API proposal: chatParticipantAdditions.
Its package.json#enabledApiProposals-property declares:  but NOT chatParticipantAdditions.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api flexpilot.flexpilot-vscode-extension
	at L (file:///c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:16650)
	at mw.fileIsIgnored (file:///c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:117:11042)
	at Object.fileIsIgnored (file:///c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:61993)
	at c:\Users\User\.vscode\extensions\flexpilot.flexpilot-vscode-extension-1.96.3-win32-x64\out\277.extension.js:1:105365
	at t.updateRuntimeArguments (c:\Users\User\.vscode\extensions\flexpilot.flexpilot-vscode-extension-1.96.3-win32-x64\out\277.extension.js:1:105568)
	at async t.activate (c:\Users\User\.vscode\extensions\flexpilot.flexpilot-vscode-extension-1.96.3-win32-x64\out\277.extension.js:1:29418)
	at async a.activate (c:\Users\User\.vscode\extensions\flexpilot.flexpilot-vscode-extension-1.96.3-win32-x64\out\extension.js:2:31394)
	at async K0.n (file:///c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4447)
	at async K0.m (file:///c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4410)
	at async K0.l (file:///c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:3866)
2025-01-09 20:00:59.202 [error] Proposed API disabled for Flexpilot
2025-01-09 20:00:59.202 [warning] Proposed API is disabled, restart required
2025-01-09 20:00:59.202 [info] GitHub Copilot is not installed.
2025-01-09 20:00:59.202 [error] Error: Flexpilot: VS Code restart required
	at t.updateRuntimeArguments (c:\Users\User\.vscode\extensions\flexpilot.flexpilot-vscode-extension-1.96.3-win32-x64\out\277.extension.js:1:106472)
	at async t.activate (c:\Users\User\.vscode\extensions\flexpilot.flexpilot-vscode-extension-1.96.3-win32-x64\out\277.extension.js:1:29418)
	at async a.activate (c:\Users\User\.vscode\extensions\flexpilot.flexpilot-vscode-extension-1.96.3-win32-x64\out\extension.js:2:31394)
	at async K0.n (file:///c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4447)
	at async K0.m (file:///c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:4410)
	at async K0.l (file:///c:/Users/User/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:115:3866)
2025-01-09 20:01:01.088 [info] No provider found for location Inline Completion

```
